In [1]:
import pandas as pd

In [2]:
dg = pd.read_csv('train.csv')

In [3]:
dg.drop(['Ticket', 'Name', 'Cabin'], axis=1, inplace=True)

In [4]:
dg

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,male,22.0,1,0,7.2500,S
1,2,1,1,female,38.0,1,0,71.2833,C
2,3,1,3,female,26.0,0,0,7.9250,S
3,4,1,1,female,35.0,1,0,53.1000,S
4,5,0,3,male,35.0,0,0,8.0500,S
5,6,0,3,male,NaN,0,0,8.4583,Q
6,7,0,1,male,54.0,0,0,51.8625,S
7,8,0,3,male,2.0,3,1,21.0750,S
8,9,1,3,female,27.0,0,2,11.1333,S
9,10,1,2,female,14.0,1,0,30.0708,C
10,11,1,3,female,4.0,1,1,16.7000,S
11,12,1,1,female,58.0,0,0,26.5500,S
12,13,0,3,male,20.0,0,0,8.0500,S
13,14,0,3,male,39.0,1,5,31.2750,S
14,15,0,3,female,14.0,0,0,7.8542,S
15,16,1,2,female,55.0,0,0,16.0000,S
16,17,0,3,male,2.0,4,1,29.1250,Q
17,18,1,2,male,NaN,0,0,13.0000,S
18,19,0,3,female,31.0,1,0,18.0000,S
19,20,1,3,female,NaN,0,0,7.2250,C
20,21,0,2,male,35.0,0,0,26.0000,S
21,22,1,2,male,34.0,0,0,13.0000,S
22,23,1,3,female,15.0,0,0,8.0292,Q
23,24,1,1,male,28.0,0,0,35.5000,S
24,25,0,3,female,8.0,3,1,21.0750,S
25,26,1,3,female,38.0,1,5,31.3875,S
26,27,0,3,male,NaN,0,0,7.2250,C
27,28,0,1,male,19.0,3,2,263.0000,S
28,29,1,3,female,NaN,0,0,7.8792,Q
29,30,0,3,male,NaN,0,0,7.8958,S
...,...,...,...,...,...,...,...,...,...
861,862,0,2,male,21.0,1,0,11.5000,S
862,863,1,1,female,48.0,0,0,25.9292,S
863,864,0,3,female,NaN,8,2,69.5500,S
864,865,0,2,male,24.0,0,0,13.0000,S
865,866,1,2,female,42.0,0,0,13.0000,S
866,867,1,2,female,27.0,1,0,13.8583,C
867,868,0,1,male,31.0,0,0,50.4958,S
868,869,0,3,male,NaN,0,0,9.5000,S
869,870,1,3,male,4.0,1,1,11.1333,S
870,871,0,3,male,26.0,0,0,7.8958,S
871,872,1,1,female,47.0,1,1,52.5542,S
872,873,0,1,male,33.0,0,0,5.0000,S
873,874,0,3,male,47.0,0,0,9.0000,S
874,875,1,2,female,28.0,1,0,24.0000,C
875,876,1,3,female,15.0,0,0,7.2250,C
876,877,0,3,male,20.0,0,0,9.8458,S
877,878,0,3,male,19.0,0,0,7.8958,S
878,879,0,3,male,NaN,0,0,7.8958,S
879,880,1,1,female,56.0,0,1,83.1583,C
880,881,1,2,female,25.0,0,1,26.0000,S
881,882,0,3,male,33.0,0,0,7.8958,S
882,883,0,3,female,22.0,0,0,10.5167,S
883,884,0,2,male,28.0,0,0,10.5000,S
884,885,0,3,male,25.0,0,0,7.0500,S
885,886,0,3,female,39.0,0,5,29.1250,Q
886,887,0,2,male,27.0,0,0,13.0000,S
887,888,1,1,female,19.0,0,0,30.0000,S
888,889,0,3,female,NaN,1,2,23.4500,S
889,890,1,1,male,26.0,0,0,30.0000,C
890,891,0,3,male,32.0,0,0,7.7500,Q

In [7]:
dg.dropna(inplace=True)
dg

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,male,22.0,1,0,7.2500,S
1,2,1,1,female,38.0,1,0,71.2833,C
2,3,1,3,female,26.0,0,0,7.9250,S
3,4,1,1,female,35.0,1,0,53.1000,S
4,5,0,3,male,35.0,0,0,8.0500,S
6,7,0,1,male,54.0,0,0,51.8625,S
7,8,0,3,male,2.0,3,1,21.0750,S
8,9,1,3,female,27.0,0,2,11.1333,S
9,10,1,2,female,14.0,1,0,30.0708,C
10,11,1,3,female,4.0,1,1,16.7000,S
11,12,1,1,female,58.0,0,0,26.5500,S
12,13,0,3,male,20.0,0,0,8.0500,S
13,14,0,3,male,39.0,1,5,31.2750,S
14,15,0,3,female,14.0,0,0,7.8542,S
15,16,1,2,female,55.0,0,0,16.0000,S
16,17,0,3,male,2.0,4,1,29.1250,Q
18,19,0,3,female,31.0,1,0,18.0000,S
20,21,0,2,male,35.0,0,0,26.0000,S
21,22,1,2,male,34.0,0,0,13.0000,S
22,23,1,3,female,15.0,0,0,8.0292,Q
23,24,1,1,male,28.0,0,0,35.5000,S
24,25,0,3,female,8.0,3,1,21.0750,S
25,26,1,3,female,38.0,1,5,31.3875,S
27,28,0,1,male,19.0,3,2,263.0000,S
30,31,0,1,male,40.0,0,0,27.7208,C
33,34,0,2,male,66.0,0,0,10.5000,S
34,35,0,1,male,28.0,1,0,82.1708,C
35,36,0,1,male,42.0,1,0,52.0000,S
37,38,0,3,male,21.0,0,0,8.0500,S
38,39,0,3,female,18.0,2,0,18.0000,S
...,...,...,...,...,...,...,...,...,...
856,857,1,1,female,45.0,1,1,164.8667,S
857,858,1,1,male,51.0,0,0,26.5500,S
858,859,1,3,female,24.0,0,3,19.2583,C
860,861,0,3,male,41.0,2,0,14.1083,S
861,862,0,2,male,21.0,1,0,11.5000,S
862,863,1,1,female,48.0,0,0,25.9292,S
864,865,0,2,male,24.0,0,0,13.0000,S
865,866,1,2,female,42.0,0,0,13.0000,S
866,867,1,2,female,27.0,1,0,13.8583,C
867,868,0,1,male,31.0,0,0,50.4958,S
869,870,1,3,male,4.0,1,1,11.1333,S
870,871,0,3,male,26.0,0,0,7.8958,S
871,872,1,1,female,47.0,1,1,52.5542,S
872,873,0,1,male,33.0,0,0,5.0000,S
873,874,0,3,male,47.0,0,0,9.0000,S
874,875,1,2,female,28.0,1,0,24.0000,C
875,876,1,3,female,15.0,0,0,7.2250,C
876,877,0,3,male,20.0,0,0,9.8458,S
877,878,0,3,male,19.0,0,0,7.8958,S
879,880,1,1,female,56.0,0,1,83.1583,C
880,881,1,2,female,25.0,0,1,26.0000,S
881,882,0,3,male,33.0,0,0,7.8958,S
882,883,0,3,female,22.0,0,0,10.5167,S
883,884,0,2,male,28.0,0,0,10.5000,S
884,885,0,3,male,25.0,0,0,7.0500,S
885,886,0,3,female,39.0,0,5,29.1250,Q
886,887,0,2,male,27.0,0,0,13.0000,S
887,888,1,1,female,19.0,0,0,30.0000,S
889,890,1,1,male,26.0,0,0,30.0000,C
890,891,0,3,male,32.0,0,0,7.7500,Q

In [14]:
dg['Embarked'] = pd.factorize(dg['Embarked'])[0]
dg['Sex'] = pd.factorize(dg['Sex'])[0]

In [15]:
dg

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,0,22.0,1,0,7.2500,0
1,2,1,1,1,38.0,1,0,71.2833,1
2,3,1,3,1,26.0,0,0,7.9250,0
3,4,1,1,1,35.0,1,0,53.1000,0
4,5,0,3,0,35.0,0,0,8.0500,0
6,7,0,1,0,54.0,0,0,51.8625,0
7,8,0,3,0,2.0,3,1,21.0750,0
8,9,1,3,1,27.0,0,2,11.1333,0
9,10,1,2,1,14.0,1,0,30.0708,1
10,11,1,3,1,4.0,1,1,16.7000,0
11,12,1,1,1,58.0,0,0,26.5500,0
12,13,0,3,0,20.0,0,0,8.0500,0
13,14,0,3,0,39.0,1,5,31.2750,0
14,15,0,3,1,14.0,0,0,7.8542,0
15,16,1,2,1,55.0,0,0,16.0000,0
16,17,0,3,0,2.0,4,1,29.1250,2
18,19,0,3,1,31.0,1,0,18.0000,0
20,21,0,2,0,35.0,0,0,26.0000,0
21,22,1,2,0,34.0,0,0,13.0000,0
22,23,1,3,1,15.0,0,0,8.0292,2
23,24,1,1,0,28.0,0,0,35.5000,0
24,25,0,3,1,8.0,3,1,21.0750,0
25,26,1,3,1,38.0,1,5,31.3875,0
27,28,0,1,0,19.0,3,2,263.0000,0
30,31,0,1,0,40.0,0,0,27.7208,1
33,34,0,2,0,66.0,0,0,10.5000,0
34,35,0,1,0,28.0,1,0,82.1708,1
35,36,0,1,0,42.0,1,0,52.0000,0
37,38,0,3,0,21.0,0,0,8.0500,0
38,39,0,3,1,18.0,2,0,18.0000,0
...,...,...,...,...,...,...,...,...,...
856,857,1,1,1,45.0,1,1,164.8667,0
857,858,1,1,0,51.0,0,0,26.5500,0
858,859,1,3,1,24.0,0,3,19.2583,1
860,861,0,3,0,41.0,2,0,14.1083,0
861,862,0,2,0,21.0,1,0,11.5000,0
862,863,1,1,1,48.0,0,0,25.9292,0
864,865,0,2,0,24.0,0,0,13.0000,0
865,866,1,2,1,42.0,0,0,13.0000,0
866,867,1,2,1,27.0,1,0,13.8583,1
867,868,0,1,0,31.0,0,0,50.4958,0
869,870,1,3,0,4.0,1,1,11.1333,0
870,871,0,3,0,26.0,0,0,7.8958,0
871,872,1,1,1,47.0,1,1,52.5542,0
872,873,0,1,0,33.0,0,0,5.0000,0
873,874,0,3,0,47.0,0,0,9.0000,0
874,875,1,2,1,28.0,1,0,24.0000,1
875,876,1,3,1,15.0,0,0,7.2250,1
876,877,0,3,0,20.0,0,0,9.8458,0
877,878,0,3,0,19.0,0,0,7.8958,0
879,880,1,1,1,56.0,0,1,83.1583,1
880,881,1,2,1,25.0,0,1,26.0000,0
881,882,0,3,0,33.0,0,0,7.8958,0
882,883,0,3,1,22.0,0,0,10.5167,0
883,884,0,2,0,28.0,0,0,10.5000,0
884,885,0,3,0,25.0,0,0,7.0500,0
885,886,0,3,1,39.0,0,5,29.1250,2
886,887,0,2,0,27.0,0,0,13.0000,0
887,888,1,1,1,19.0,0,0,30.0000,0
889,890,1,1,0,26.0,0,0,30.0000,1
890,891,0,3,0,32.0,0,0,7.7500,2

In [ ]:
from pandas.tools.plotting import scatter_matrix
%matplotlib inline
import matplotlib.pyplot as plt
dg.hist()
plt.show()

In [17]:

p = scatter_matrix(dg, figsize=(15, 15))

In [18]:
print p

[[<matplotlib.axes._subplots.AxesSubplot object at 0x112e5bd90>
  <matplotlib.axes._subplots.AxesSubplot object at 0x11387fcd0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x113901b50>
  <matplotlib.axes._subplots.AxesSubplot object at 0x113964e10>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1139e6c90>
  <matplotlib.axes._subplots.AxesSubplot object at 0x113a58990>
  <matplotlib.axes._subplots.AxesSubplot object at 0x113ae1b50>
  <matplotlib.axes._subplots.AxesSubplot object at 0x113b669d0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x113bd5490>]
 [<matplotlib.axes._subplots.AxesSubplot object at 0x113c58410>
  <matplotlib.axes._subplots.AxesSubplot object at 0x113cbc350>
  <matplotlib.axes._subplots.AxesSubplot object at 0x113d3f2d0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x113d793d0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x113e33150>
  <matplotlib.axes._subplots.AxesSubplot object at 0x113ea7f90>
  <matplotlib.axes._subplots.AxesSubplot object at 0x113f1c110>
  <matplotlib.axes._subplots.AxesSubplot object at 0x113f90f50>
  <matplotlib.axes._subplots.AxesSubplot object at 0x113ff8c50>]
 [<matplotlib.axes._subplots.AxesSubplot object at 0x114080d50>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114105bd0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114160990>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1141e4650>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114254510>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1142de450>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1143653d0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1143c6590>
  <matplotlib.axes._subplots.AxesSubplot object at 0x11444a5d0>]
 [<matplotlib.axes._subplots.AxesSubplot object at 0x1144ad550>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114530650>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1144d1b50>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114622550>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1146a73d0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x11470a9d0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x11478e850>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1147f3890>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114875810>]
 [<matplotlib.axes._subplots.AxesSubplot object at 0x1148af810>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1149665d0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1149ec450>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114a4f710>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114ad2590>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114b3b290>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114bc42d0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114c48150>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114ca9c50>]
 [<matplotlib.axes._subplots.AxesSubplot object at 0x114d2ead0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x11411dcd0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114e03110>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114e78f50>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114ee7b50>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114f6a9d0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x114fcea10>
  <matplotlib.axes._subplots.AxesSubplot object at 0x115052990>
  <matplotlib.axes._subplots.AxesSubplot object at 0x11508a990>]
 [<matplotlib.axes._subplots.AxesSubplot object at 0x115144750>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1151c95d0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x11522d890>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1152af710>
  <matplotlib.axes._subplots.AxesSubplot object at 0x115317410>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1153a2450>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1154252d0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x115487dd0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x11550cc50>]
 [<matplotlib.axes._subplots.AxesSubplot object at 0x11556fc90>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1155f2c10>
  <matplotlib.axes._subplots.AxesSubplot object at 0x115601b50>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1156e49d0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x115767850>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1157cbb10>
  <matplotlib.axes._subplots.AxesSubplot object at 0x11584f990>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1158b8690>
  <matplotlib.axes._subplots.AxesSubplot object at 0x1159426d0>]
 [<matplotlib.axes._subplots.AxesSubplot object at 0x1159c4550>
  <matplotlib.axes._subplots.AxesSubplot object at 0x115a1e090>
  <matplotlib.axes._subplots.AxesSubplot object at 0x115aa2690>
  <matplotlib.axes._subplots.AxesSubplot object at 0x115afabd0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x115b95090>
  <matplotlib.axes._subplots.AxesSubplot object at 0x115bcd190>
  <matplotlib.axes._subplots.AxesSubplot object at 0x115c79bd0>
  <matplotlib.axes._subplots.AxesSubplot object at 0x115cfda50>
  <matplotlib.axes._subplots.AxesSubplot object at 0x115d62990>]]